[tool]
id = "com.thelightphone.authenticator"
label = "Authenticator"
versionCode = 2
versionName = "2.0.0"
permissions = ["android.permission.CAMERA"]
# change if you run this on the emulator!
# serverPackage = "com.thelightphone.sdk.emulator"
serverPackage = "com.lightos"
