[tool]
id = "com.thelightphone.training"
label = "Training"
versionCode = 5
versionName = "0.2.2"
permissions = ["android.permission.INTERNET"]
capabilities = []
# change if you run this on an LP3!
# serverPackage = "com.lightos"
serverPackage = "com.thelightphone.sdk.emulator"
